name: pipx integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: ["3.8", "3.10", "3.12"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone gyp-next
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Setup dependencies
        shell: bash
        run: |
          python3 -m pip install --user pipx
      - name: Integration test with pipx
        shell: bash
        run: |
          pipx run --no-cache --spec ./ gyp --help
          pipx run --no-cache --spec ./ gyp --version
